//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/CreateObject.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CreateObject: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CreateObject()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CreateObject"",
    ""maps"": [
        {
            ""name"": ""ControlsObject"",
            ""id"": ""3ab1bdaa-331a-44e3-ab42-8c580e834cd0"",
            ""actions"": [
                {
                    ""name"": ""Create"",
                    ""type"": ""Button"",
                    ""id"": ""ff3c5488-d0f2-46be-ac34-6ce3de23c57a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""634254b6-dbe3-4337-81a6-883a8e6e44fe"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Create"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // ControlsObject
        m_ControlsObject = asset.FindActionMap("ControlsObject", throwIfNotFound: true);
        m_ControlsObject_Create = m_ControlsObject.FindAction("Create", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // ControlsObject
    private readonly InputActionMap m_ControlsObject;
    private List<IControlsObjectActions> m_ControlsObjectActionsCallbackInterfaces = new List<IControlsObjectActions>();
    private readonly InputAction m_ControlsObject_Create;
    public struct ControlsObjectActions
    {
        private @CreateObject m_Wrapper;
        public ControlsObjectActions(@CreateObject wrapper) { m_Wrapper = wrapper; }
        public InputAction @Create => m_Wrapper.m_ControlsObject_Create;
        public InputActionMap Get() { return m_Wrapper.m_ControlsObject; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControlsObjectActions set) { return set.Get(); }
        public void AddCallbacks(IControlsObjectActions instance)
        {
            if (instance == null || m_Wrapper.m_ControlsObjectActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_ControlsObjectActionsCallbackInterfaces.Add(instance);
            @Create.started += instance.OnCreate;
            @Create.performed += instance.OnCreate;
            @Create.canceled += instance.OnCreate;
        }

        private void UnregisterCallbacks(IControlsObjectActions instance)
        {
            @Create.started -= instance.OnCreate;
            @Create.performed -= instance.OnCreate;
            @Create.canceled -= instance.OnCreate;
        }

        public void RemoveCallbacks(IControlsObjectActions instance)
        {
            if (m_Wrapper.m_ControlsObjectActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IControlsObjectActions instance)
        {
            foreach (var item in m_Wrapper.m_ControlsObjectActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_ControlsObjectActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public ControlsObjectActions @ControlsObject => new ControlsObjectActions(this);
    public interface IControlsObjectActions
    {
        void OnCreate(InputAction.CallbackContext context);
    }
}
